Instagram_Clone/Controllers/ExploreController.cs
using Instagram_Clone.Repositories.PostRepo;
using Microsoft.AspNetCore.Mvc;

namespace Instagram_Clone.Controllers
{
    public class ExploreController : Controller
    {
        public IPostRepository PostRepository;

        public ExploreController(IPostRepository _postRepository) 
        {
            PostRepository = _postRepository;
        }


        public IActionResult Index()
        {
           List<Post>? posts = PostRepository.GetAllPosts();

            List<string> paths = new List<string>();

            foreach(var post in posts)
            {
                paths.Add(post.PhotosPathes.First());
            }

            ViewBag.paths = paths;
            return View("Index", posts);
        }

        public IActionResult openPost(int postId)
        {
            Post post = PostRepository.GetPostwithUserAndCommentsAndFollowersById(postId);

            return RedirectToAction("Index", "Profile", new { UserId = post.UserId });
            //return View("openPost", post);
        }
    }
}

Instagram_Clone/Views/Explore/Index.cshtml
@model List<Post>



<div class="container-fluid">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="container mt-3">
                @for (int index = 0; index < Model.Count; index += 2)
                {
                    <div class="row mb-4">
                        <div class="col-md-6 mb-2">
                            <form method="post" action="@Url.Action("openPost", "Explore")" class="postForm">
                                <input type="hidden" name="postId" value="@Model[index].Id" />
                                <img width="100%" src="~/images/@ViewBag.paths[index]" class="postImage">
                            </form>
                        </div>
                        @if (index + 1 < Model.Count)
                        {
                            <div class="col-md-6">
                                <form method="post" action="@Url.Action("openPost", "Explore")" class="postForm">
                                    <input type="hidden" name="postId" value="@Model[index + 1].Id" />
                                    <img width="100%" src="~/images/@ViewBag.paths[index + 1]" class="postImage">
                                </form>
                            </div>
                        }
                    </div>
                }
            </div>
        </div>
    </div>
</div>



<style>
    img:hover
    {
        cursor: pointer;
        height:max-content;
    }


</style>


<script>
    document.addEventListener('DOMContentLoaded', function () {
        var postForms = document.querySelectorAll('.postForm');
        postForms.forEach(function (form) {
            form.addEventListener('click', function () {
                this.submit();
            });
        });
    });


</script>