Instagram_Clone/Controllers/PostController.cs
using Instagram_Clone.Models.photo;
using Instagram_Clone.Repositories.CommentRepo;
using Instagram_Clone.Repositories.PhotoRepo;
using Instagram_Clone.Repositories.PhotoRepo.postPhotoContainer;
using Instagram_Clone.Repositories.PostRepo;
using Instagram_Clone.ViewModels;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace Instagram_Clone.Controllers
{
    public class PostController : Controller
    {
        private readonly Context context;
        private readonly IPostRepository postRepository;
        private readonly IWebHostEnvironment webHostEnvironment;
        private readonly IpostPhotoRepository photoRepository;
        private readonly ICommentRepository commentRepository;

        public PostController(Context context,IPostRepository postRepository, IWebHostEnvironment webHostEnvironment, IpostPhotoRepository photoRepository , ICommentRepository commentRepository)
        {
            this.context = context;
            this.postRepository = postRepository;
            this.webHostEnvironment = webHostEnvironment;
            this.photoRepository = photoRepository;
            this.commentRepository = commentRepository;
        } 
        public IActionResult Add()
        {
            return View("Add");
        }


        public IActionResult SaveAdd(AddPostVM postVM)
        {

            string uploadPath = Path.Combine(webHostEnvironment.WebRootPath, "images");
            string name = Guid.NewGuid().ToString() + "_" + postVM.Image.FileName;
            string filePath = Path.Combine(uploadPath, name);
            using (FileStream fileStream = new FileStream(filePath, FileMode.Create))
            {
                postVM.Image.CopyTo(fileStream);
            }

            //photo.Path = name;

            Claim claim = User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier);
            ApplicationUser user = context.Users.FirstOrDefault(u => u.Id == claim.Value);

            Post post = new Post();
            post.Caption = postVM.Caption;
            //post.Photos = new List<string> ();
            List<string> Pathes = new List<string>();
            Pathes.Add(filePath);

            post.PhotosPathes.Add(name);
            post.UserId = user.Id;
            postRepository.Insert(post);
            postRepository.Save();

            postPhoto photo = new postPhoto();
            photo.Path = filePath;
            photo.Name = name;
            photo.PostId = post.Id;
            photoRepository.Insert(photo);
            photoRepository.Save();
            ViewBag.Name = name;

            //foreach (var item in post.Photos)
            //{
            //    photoRepository.Insert(item);
            //    photoRepository.Save();
            //}

            //< img src = "D:\Mvc\project\Instagram_Clone\wwwroot\images\71ed0bca-c360-4885-ac83-458d38a18d3e_oii.jpeg" style = "width:100px; height:100px;" >


            // return View("SaveAdd", post);
            return RedirectToAction("Index", "Home");
        }

        //List<PostViewModel> posts = new List<PostViewModel>();
        //PostViewModel post = new PostViewModel();
        //post.Caption = "kerollos";
        //posts.Add(post);   
        //List<PostViewModel> postList = new List<PostViewModel>();
        //postList.Add(postViewModel);


        public IActionResult Comment(int postId)
        {


            Post? post = postRepository.GetPostwithUserAndCommentsAndFollowersById(postId);
            List<CommentViewModel> comments = new List<CommentViewModel>();

            if (post.Comments != null)
            {
                foreach (var comment in post.Comments)
                {
                    CommentViewModel commentView = new CommentViewModel();
                    commentView.ProfilePicture = comment.User.ProfilePicture.Name;
                    
                    commentView.Content = comment.Content;
                    commentView.UserName = comment.User.UserName;

                    TimeSpan TimeSincePost = DateTime.Now - comment.Date;
                    if (TimeSincePost.TotalSeconds < 60)
                        commentView.TimeAgo = $"{(int)TimeSincePost.TotalSeconds} second ago";
                    else if (TimeSincePost.TotalMinutes < 60)
                        commentView.TimeAgo = $"{(int)TimeSincePost.TotalMinutes} minute ago";
                    else if (TimeSincePost.TotalHours < 24)
                        commentView.TimeAgo = $"{(int)TimeSincePost.TotalHours} hour ago";
                    else
                        commentView.TimeAgo = $"{(int)TimeSincePost.TotalDays} day ago";

                    comments.Add(commentView);
                }

                

            }
            //ViewBag.picture = comments[0].ProfilePicture;
            return Json(comments);
           
        }

        //public IActionResult DeletePost(int postId)
        //{

        //}

        public IActionResult SaveComment(int postId , string comment)
        {

            Claim claim = User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier);
            ApplicationUser user = context.Users.FirstOrDefault(u => u.Id == claim.Value);

            Comment commentObj = new Comment
            {
                Content = comment,
                Date = DateTime.Now,
                UserId = user.Id,
                PostId = postId
            };

            commentRepository.Insert(commentObj);
            commentRepository.Save();

            return RedirectToAction("Index", "Home");
            
        }

        public IActionResult Delete(int postId)
        {
            Post? post = postRepository.GetPostByIDWithUser(postId);
            Claim claim = User.Claims.FirstOrDefault(c => c.Type == ClaimTypes.NameIdentifier);
            ApplicationUser user = context.Users.FirstOrDefault(u => u.Id == claim.Value);

            if(post != null)
            {
                if(post.User.Id == user.Id)
                {
                    post.IsDeleted = true;
                    postRepository.Update(post);
                    postRepository.Save();
                    //return Json("deleted succss");

                    return Json("deleted success");
                }
                return Json("not match");
            }


            return Json("deleted not succss");
            //return View("_DeletePost");
        
        }
    }
}

Instagram_Clone/Controllers/StoryController.cs
using Instagram_Clone.Models;
using Instagram_Clone.Repositories.MessageRepo;
using Instagram_Clone.Repositories.StoryRepo;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Instagram_Clone.Controllers
{
    public class StoryController: Controller
    {
        public readonly IStoryRepository storyRepository;
        public readonly UserManager<ApplicationUser> userManager;
        private readonly IWebHostEnvironment webHostEnvironment;

        public StoryController(IWebHostEnvironment webHostEnvironment,IStoryRepository _storyRepository, UserManager<ApplicationUser> _userManager)
        {
            storyRepository = _storyRepository;
            userManager = _userManager;
            this.webHostEnvironment = webHostEnvironment;
        }

        public async Task<IActionResult> Index()
        {
            var user = await userManager.GetUserAsync(User);
            var userId = user.Id;

            var stories = storyRepository.GetAllStories(userId);

            return View(stories);
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Add(IFormFile Image, IFormFile Audio)
        {
            ApplicationUser currentUser = await userManager.GetUserAsync(User);

            string uploadPath = Path.Combine(webHostEnvironment.WebRootPath, "images");
            string name = Guid.NewGuid().ToString() + "_" + Image.FileName;
            string filePath = Path.Combine(uploadPath, name);
            using (FileStream fileStream = new FileStream(filePath, FileMode.Create))
            {
                Image.CopyTo(fileStream);
            }

            var photo = new storyPhoto
            {
                Path = filePath,
                Name = name,
                IsDeleted = false
            };

            var story = new Story
            {
                CreatedAt = DateTime.Now,
                LifeTimeTicks = TimeSpan.FromHours(24).Ticks,
                IsDeleted = false,
                UserId = currentUser.Id,
                Photo = photo
            };

            // Process the audio file
            if (Audio != null && Audio.Length > 0)
            {
                string uploadPathAudio = Path.Combine(webHostEnvironment.WebRootPath, "audio");
                string audioName = Guid.NewGuid().ToString() + "_" + Audio.FileName;
                string audioFilePath = Path.Combine(uploadPathAudio, audioName);
                using (FileStream fileStream = new FileStream(audioFilePath, FileMode.Create))
                {
                    Audio.CopyTo(fileStream);
                }

                // Store the audio file path along with the story
                story.AudioPath = audioFilePath;
            }

            storyRepository.Insert(story);
            storyRepository.Save();


            return RedirectToAction("Index", "Home");
        }

        public IActionResult OpenStory(string storyPic, DateTime time, string audio) 
        {


            TimeSpan timeSinceCreation = DateTime.Now - time;
            string timeSinceCreationString;

            if (timeSinceCreation.TotalMinutes < 60)
            {
                timeSinceCreationString = $"{(int)timeSinceCreation.TotalMinutes} minutes ago";
            }
            else if (timeSinceCreation.TotalHours < 24)
            {
                timeSinceCreationString = $"{(int)timeSinceCreation.TotalHours} hours ago";
            }
            else
            {
                timeSinceCreationString = $"{(int)timeSinceCreation.TotalDays} days ago";
            }



            ViewBag.TimeSinceCreation = timeSinceCreationString;
            ViewBag.StoryPic = storyPic;
            ViewBag.audio = Path.GetFileName(audio);

            return View("OpenStory"); 
        }
    }
}

Instagram_Clone/Views/Home/GoToAllUsers.cshtml
@using Instagram_Clone.ViewModels
@using Instagram_Clone.Authentication
@model List<ApplicationUser>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Instagram Followers & Following List</title>
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="tryfollow.css">
</head>
<body>
    <form class="form-inline" id="searchForm" method="get" asp-action="GoToAllUsers" asp-controller="Home">
        <input class="form-control me-2" placeholder="Search..." id="NameSearch" name="Name" type="text">
@*         <button type="submit" class="btn btn-primary">Search</button>
 *@    </form>
    <div class="container mt-5">
        <div class="d-flex justify-content-center row">
            <div class="col-md-6" id="searchResults">
                @foreach (var follower in Model)
                {
                    <div class="p-3 bg-white text-center">
                        <div class="d-flex flex-row justify-content-between align-items-center mt-2">
                            <img class="rounded-circle" src="/images/@follower.?ProfilePicture.Name" width="55">
                            <div class="d-flex flex-column align-items-start ml-2">
                                <a class="font-weight-bold" href="/FriendsProfile/index/@follower.Id">@follower.UserName</a>

                            </div>
                            @* <div class="d-flex flex-row align-items-center">
                                <div class="d-flex flex-row align-items-center mt-2">
                                    <a href="/Follow/RemoveFollower/@follower.Id" class="btn btn-primary btn-sm" type="button">Remove</a>
                                </div>
                            </div> *@
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>

    <link rel="stylesheet" href="//code.jquery.com/ui/1.13.2/themes/base/jquery-ui.css">
    <script>
        document.addEventListener("DOMContentLoaded", function () {
            var input = document.getElementById("NameSearch")
            input.addEventListener("input", function () {
                // Fetch data using AJAX based on the search input
                var searchTerm = input.value;
                // Example AJAX call
                // Replace this with your actual AJAX call to fetch followers based on search term
                fetch("/Home/GoToAllUsers?Name=" + searchTerm)
                    .then(response => response.text())
                    .then(data => {
                        // Create a temporary element to hold the fetched data
                        var tempElement = document.createElement('div');
                        tempElement.innerHTML = data;
                        // Select only the elements you want to append
                        var followers = tempElement.querySelectorAll('.p-3.bg-white.text-center');
                        // Append each follower element to the existing content
                        document.getElementById("searchResults").innerHTML = "";
                        followers.forEach(function (follower) {
                            document.getElementById("searchResults").appendChild(follower);
                        });
                    })
                    .catch(error => {
                        console.error('Error:', error);
                    });
            });
        });
    </script>

</body>
</html>

Instagram_Clone/Views/Home/_CommentPartial.cshtml
@* 
    
    <div class="modal fade" id="message_modal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">Comments</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <h1>messi</h1>
                <div class="modal-body">
                    <div class="comments">
                        <div class="comment">
                        @if(ViewBag.Comments != null)
                        {
                            
                        
                            @foreach(var comment in ViewBag.Comments)
                            {
                                <div class="d-flex">
                                    <div class="img">
                                        <img src="/images/profile_img.jpg" alt="">
                                    </div>
                                    <div class="content">
                                        <div class="person">
                                            <span>3j</span>


                                        </div>
                                         <p>Wow amzing shot</p> 
                                        <p>@comment.Content</p>
                                        <div class="replay">
                                            <button class="replay">replay</button>
                                            <button class="translation">see translation</button>
                                        </div>
                                        <div class="answers">
                                            <button class="see_comment">
                                                <span class="hide_com">Hide all responses</span>
                                                <span class="show_c">
                                                    <span class="line"></span> See the <span>
                                                        1
                                                    </span> answers
                                                </span>
                                            </button>
                                        </div>

                                    </div>
                                </div>
                                <div class="like">
                                    <img class="not_loved" src="/images/love.png" alt="">
                                    <img class="loved" src="/images/heart.png" alt="">
                                    <p> 55</p>

                                </div>
                                     </div> 
                                }
                        }
                        else
                        {
                            <h1>not comments </h1>
                        }

                        <div class="responses">
                            <div class="response comment">
                                <div class="d-flex">
                                    <div class="img">
                                        <img src="/images/profile_img.jpg" alt="">
                                    </div>
                                    <div class="content">
                                        <div class="person">
                                            <h4>namePerson</h4>
                                            <span>3j</span>

                                        </div>
                                        <p>Wow amzing shot</p>
                                        <div class="replay">
                                            <button>replay</button>
                                            <button>see translation</button>
                                        </div>

                                    </div>
                                </div>
                                <div class="like">
                                    <img class="not_loved" src="/images/love.png" alt="">
                                    <img class="loved" src="/images/heart.png" alt="">
                                    <p> 55</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            
                <div class="modal-footer">
                    <form method="post">
                        <div class="input">
                            <img src="/images/profile_img.jpg" alt="">
                            <input type="text" id="emoji_comment" placeholder="Add a comment..." />
                        </div>

                        <input type="submit" asp-controller="Post" asp-action="SaveComment"/>
                        <!-- <div class="emogi">
                            <img src="/images/emogi.png" alt="">
                        </div> -->
                    </form>
                </div>
            </div>
        </div>
    </div>

   @*  <script>
        var hub2 = new signalR.HubConnectionBuilder().withUrl("/PostH").build();


        hub2.on("ReceiveComments" , function(comments){
            console.log("hello wessa");
        })

    </script> *@
<div class="modal fade" id="message_modal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title fs-5" id="exampleModalLabel">Comments</h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <div id="commentsId" class="comments">
                </div>


                <div class="modal-footer">
                    <form method="post">
                        <div class="input">
                            <img src="/images/profile_img.jpg" alt="">
                            <input type="text" id="emoji_comment" name="comment" placeholder="Add a comment..." />
                            <input type="hidden" id="postIdInput" name="postId" />
                        </div>

                        <input type="submit" asp-controller="Post" asp-action="SaveComment" style="display:none;" />
                        <!-- <div class="emogi">
                            <img src="/images/emogi.png" alt="">
                        </div> -->
                    </form>
                </div>
            </div>
        </div>
    </div>

Instagram_Clone/Views/Home/_StoryPartial.cshtml
@* <div class="stories">
    <div class="owl-carousel items">
        <div class="item_s">
            <img src="https://fakeimg.pl/300/">
            <p>loy</p>

        </div>
    </div>

</div>
 *@



 <div class="stories">


    <div class="owl-carousel">
        <!-- Corrected class name -->
        <div class="story">
            <a asp-action="Add" asp-controller="Story">
                <img src="~/images/addStory.png"/>
            </a>
        </div>

        @foreach (var story in ViewBag.myStories)
        {
            <div class="story">
                <a asp-action="OpenStory" asp-controller="story" asp-route-storyPic="@story.Photo.Name" asp-route-time="@story.CreatedAt" asp-route-audio="@story.AudioPath">
                    <img src="~/images/@story.User.ProfilePicture?.Name" alt="Story">

                </a>
            </div>
        }
        @foreach (var story in ViewBag.Stories)
        {
            <div class="story">
                <a asp-action="OpenStory" asp-controller="story">
                    <img src="~/images/@story.User.ProfilePicture?.Name" alt="Story">

                </a>
            </div>
        }



    </div>
</div>

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.theme.default.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css" integrity="sha512-Xn7wbl9jMchZnyxOdK0/ty6T/F7Mb3uID+lcSULm77qcv+o2Nm6iZIvHVZ5lcS2HHlFJwM3GOhJnmZ2hzyh0ug==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<style>
    body {
        font-family: Arial, sans-serif;
        margin: 0;
        padding: 0;
    }

    .story-container {
        display: flex;
        overflow-x: auto;
        overflow-y: hidden;
        padding: 5px;
    }

    .story {
        margin: 0px !important;
        border-radius: 50%;
        overflow: hidden;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
        border: 2px solid #ff0566;
    }

        .story img {
            width: 100%;
            height: 100%;
            object-fit: cover;
            cursor: pointer;
        }

    .owl-stage {
        display: flex;

        gap: 20px;

    }

    .owl-item {
        width: 100px !important;
    }

        .owl-item.active {
            width: 100px !important;
        }

    .owl-carousel .owl-stage:after {
        content: '';
        display: none;
    }

</style>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js"></script>
    <script>
    jQuery(document).ready(function ($) {
        $('.owl-carousel').owlCarousel({
            loop: false,
            margin: 10,
            nav: true,
            responsive: {
                0: {
                    items: 1
                },
                600: {
                    items: 3
                },
                1000: {
                    items: 5
                }
            }
        })
     });
    </script>

Instagram_Clone/Views/Home/_TestPartial.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
<!--Create model-->



<div class="modal fade" id="create_modal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
        <div class="modal-content">
            <div class="modal-header">
                <h1 class="modal-title w-100 fs-5 d-flex align-items-end justify-content-between"
                    id="exampleModalLabel">
                    <span class="title_create">Create new post</span>
                    <button class="next_btn_post btn_link"></button>
                </h1>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <img class="up_load" src="/images/upload.png" alt="upload">
                <p>Drag photos and videos here</p>
                <button class="btn btn-primary btn_upload">
                    select from your computer
                    <form id="upload-form">
                        <input class="input_select" type="file" id="image-upload" name="image-upload">
                    </form>
                </button>
                <div id="image-container" class="hide_img">
                </div>
                <div id="image_description" class="hide_img">
                    <div class="img_p"></div>
                    <div class="description">
                        <div class="cart">
                            <div>
                                <div class="img">
                                    <img src="/images/profile_img.jpg">
                                </div>
                                <div class="info">
                                    <p class="name">Zineb_essoussi</p>
                                </div>
                            </div>
                        </div>
                        <form>
                            <textarea type="text" id="emoji_create" placeholder="write your email"></textarea>
                        </form>
                    </div>
                </div>
                <div class="post_published hide_img">
                    <img src="/images/uploaded_post.gif" alt="">
                </div>
            </div>
        </div>
    </div>
</div>

    </div>